# TCL File Generated by Component Editor 18.1
# Thu Jan 11 13:31:00 CET 2024
# DO NOT MODIFY


# 
# acc_scale "acc_scale" v1.0
# DT 2024.01.11.13:31:00
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module acc_scale
# 
set_module_property DESCRIPTION ""
set_module_property NAME acc_scale
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Accelerators
set_module_property AUTHOR DT
set_module_property DISPLAY_NAME acc_scale
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL acc_scale
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file acc_scale.vhd VHDL PATH acc_scale.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter G_MAX_ROW_WIDTH INTEGER 10
set_parameter_property G_MAX_ROW_WIDTH DEFAULT_VALUE 10
set_parameter_property G_MAX_ROW_WIDTH DISPLAY_NAME G_MAX_ROW_WIDTH
set_parameter_property G_MAX_ROW_WIDTH TYPE INTEGER
set_parameter_property G_MAX_ROW_WIDTH UNITS None
set_parameter_property G_MAX_ROW_WIDTH HDL_PARAMETER true
add_parameter G_SCALE_WIDTH INTEGER 3
set_parameter_property G_SCALE_WIDTH DEFAULT_VALUE 3
set_parameter_property G_SCALE_WIDTH DISPLAY_NAME G_SCALE_WIDTH
set_parameter_property G_SCALE_WIDTH TYPE INTEGER
set_parameter_property G_SCALE_WIDTH UNITS None
set_parameter_property G_SCALE_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avs_params
# 
add_interface avs_params avalon end
set_interface_property avs_params addressUnits SYMBOLS
set_interface_property avs_params associatedClock clock
set_interface_property avs_params associatedReset reset
set_interface_property avs_params bitsPerSymbol 8
set_interface_property avs_params bridgedAddressOffset 0
set_interface_property avs_params burstOnBurstBoundariesOnly false
set_interface_property avs_params burstcountUnits WORDS
set_interface_property avs_params explicitAddressSpan 0
set_interface_property avs_params holdTime 0
set_interface_property avs_params linewrapBursts false
set_interface_property avs_params maximumPendingReadTransactions 0
set_interface_property avs_params maximumPendingWriteTransactions 0
set_interface_property avs_params readLatency 0
set_interface_property avs_params readWaitTime 1
set_interface_property avs_params setupTime 0
set_interface_property avs_params timingUnits Cycles
set_interface_property avs_params writeWaitTime 0
set_interface_property avs_params ENABLED true
set_interface_property avs_params EXPORT_OF ""
set_interface_property avs_params PORT_NAME_MAP ""
set_interface_property avs_params CMSIS_SVD_VARIABLES ""
set_interface_property avs_params SVD_ADDRESS_GROUP ""

add_interface_port avs_params avs_params_address address Input 4
add_interface_port avs_params avs_params_read read Input 1
add_interface_port avs_params avs_params_readdata readdata Output 8
add_interface_port avs_params avs_params_write write Input 1
add_interface_port avs_params avs_params_writedata writedata Input 8
add_interface_port avs_params avs_params_waitrequest waitrequest Output 1
set_interface_assignment avs_params embeddedsw.configuration.isFlash 0
set_interface_assignment avs_params embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_params embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_params embeddedsw.configuration.isPrintableDevice 0


# 
# connection point asi_in
# 
add_interface asi_in avalon_streaming end
set_interface_property asi_in associatedClock clock
set_interface_property asi_in associatedReset reset
set_interface_property asi_in dataBitsPerSymbol 8
set_interface_property asi_in errorDescriptor ""
set_interface_property asi_in firstSymbolInHighOrderBits true
set_interface_property asi_in maxChannel 0
set_interface_property asi_in readyLatency 0
set_interface_property asi_in ENABLED true
set_interface_property asi_in EXPORT_OF ""
set_interface_property asi_in PORT_NAME_MAP ""
set_interface_property asi_in CMSIS_SVD_VARIABLES ""
set_interface_property asi_in SVD_ADDRESS_GROUP ""

add_interface_port asi_in asi_in_data data Input 8
add_interface_port asi_in asi_in_ready ready Output 1
add_interface_port asi_in asi_in_valid valid Input 1
add_interface_port asi_in asi_in_eop endofpacket Input 1
add_interface_port asi_in asi_in_sop startofpacket Input 1


# 
# connection point aso_out
# 
add_interface aso_out avalon_streaming start
set_interface_property aso_out associatedClock clock
set_interface_property aso_out associatedReset reset
set_interface_property aso_out dataBitsPerSymbol 8
set_interface_property aso_out errorDescriptor ""
set_interface_property aso_out firstSymbolInHighOrderBits true
set_interface_property aso_out maxChannel 0
set_interface_property aso_out readyLatency 0
set_interface_property aso_out ENABLED true
set_interface_property aso_out EXPORT_OF ""
set_interface_property aso_out PORT_NAME_MAP ""
set_interface_property aso_out CMSIS_SVD_VARIABLES ""
set_interface_property aso_out SVD_ADDRESS_GROUP ""

add_interface_port aso_out aso_out_data data Output 8
add_interface_port aso_out aso_out_ready ready Input 1
add_interface_port aso_out aso_out_valid valid Output 1
add_interface_port aso_out aso_out_eop endofpacket Output 1
add_interface_port aso_out aso_out_sop startofpacket Output 1

